- DocumentFormat.OpenXml/src/Framework/OpenXmlSimpleType.cs
- DocumentFormat.OpenXml/src/Framework/OpenXmlWriter.cs
- DocumentFormat.OpenXml/src/ofapi/ExtensionMethods.cs
- DocumentFormat.OpenXml/src/ofapi/PackageDocument.cs
This updates the project for some reflection changes that are not compatible with .NET Standard
> Update reflection for .NET Standard

- DocumentFormat.OpenXml/project.json
- DocumentFormat.OpenXml/src/Framework/ExceptionMessages.Designer.cs
- DocumentFormat.OpenXml/src/Framework/OpenXmlSimpleType.cs
- DocumentFormat.OpenXml/src/Framework/OpenXmlWriter.cs
- DocumentFormat.OpenXml/src/Framework/PartContainer.cs
- DocumentFormat.OpenXml/src/ofapi/ExtensionMethods.cs
- DocumentFormat.OpenXml/src/ofapi/Validation/SchemaValidation/SchemaTypeData.cs
- DocumentFormat.OpenXml/src/ofapi/Validation/SemanticValidation/SemanticConstraint/RootAttributeUniqueConstraint.cs
- DocumentFormat.OpenXml/src/ofapi/Validation/SemanticValidation/SemanticConstraint/UniqueAttributeValueConstraint.cs
- DocumentFormat.OpenXml/src/ofapi/Validation/ValidationResources.Designer.cs
I missed a few on a previous PR, so this takes care of the rest.
Part of #111
> Replace some APIs with .NET Standard supported ones

- README.md
- appveyor.yml
> Add MyGet feed deployment

- README.md
- appveyor.yml
> Update MyGet key

- README.md
Fix Markdown formatting for NuGet-Headlines.
> Fix formatting for headlines

- DocumentFormat.OpenXml.Tests/OpenXmlDomTest/CodeGenSanityTest.cs
- DocumentFormat.OpenXml.Tests/TestFileStreams.cs
> Use theories for CodeGenSanityTests

- DocumentFormat.OpenXml.Package.props
- ISSUE_TEMPLATE.md
- README.md
> Update README with known issues and fixes for changelog

- Directory.Build.props
- DocumentFormat.OpenXml.Tests/Common/VerifiableLog.cs
- DocumentFormat.OpenXml.Tests/ConformanceTest/WebExtension/WebExtensionTest.cs
- DocumentFormat.OpenXml.Tests/OpenXmlDomTaskLibrary/TestScripts/OpenXmlTestBase.cs
- DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs
- DocumentFormat.OpenXml.Tests/OpenXmlDomTest/OpenXmlDomTestBase.cs
- DocumentFormat.OpenXml.Tests/OpenXmlDomTest/OpenXmlReaderWriterTest.cs
- DocumentFormat.OpenXml.Tests/OpenXmlDomTest/PackageReflector.cs
- DocumentFormat.OpenXml.Tests/OpenXmlDomTest/SimpleTypeTest.cs
- DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlElementTest.cs
- DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlReaderTest.cs
- DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlSimpleValueTest2.cs
- DocumentFormat.OpenXml.Tests/ofapiTest/SdbSchemaDatasTest.cs
- DocumentFormat.OpenXml/src/Framework/AlternateContent.cs
- DocumentFormat.OpenXml/src/Framework/OpenXmlAttribute.cs
- DocumentFormat.OpenXml/src/Framework/OpenXmlElement.cs
- DocumentFormat.OpenXml/src/Framework/OpenXmlSimpleType.cs
- DocumentFormat.OpenXml/src/Framework/PartContainer.cs
- DocumentFormat.OpenXml/src/ofapi/Validation/SchemaValidation/BinarySdbSchemaDatas.cs
- DocumentFormat.OpenXml/src/ofapi/Validation/SchemaValidation/SchemaTypeData.cs
- DocumentFormat.OpenXml/src/ofapi/Validation/SchemaValidation/SdbSchemaDatas.cs
- DocumentFormat.OpenXml/src/ofapi/Validation/SchemaValidation/SimpleTypes.cs
- rules.ruleset
> Enable SA1119 to remove unnecessary parentheses

- appveyor.yml
- build/SignClientSettings.json
- build/SignPackage.ps1
This PR is to move to the new sign service. Please contact me on how to share the secrets with you.
These changes should be cherry-picked & applied to all branches you plan to build from as we want to deprecate the old service.
Thanks
> Use SignService v2

- DocumentFormat.OpenXml/OpenXmlElementExtensionMethods.cs
> Move extension methods to own file

- appveyor.yml
#328 Had encrypted the variables under the wrong account. This should fix the build break.
> Update secure build variables

- appveyor.yml
The file produced it >100mb and too large for CodeCov to process at the
moment. Disabling this for now.
> Disable code coverage

- README.md
I made a few changes in the content, fixed all the lint errors and warnings that VS Code showed, and added a table of contents.
> suggesting content changes, fixing lint errors & warnings, and adding table of contents

- DocumentFormat.OpenXml.Package.props
> LICENSE.txt reference should be LICENSE

- README.md
Removing extraneous space before colon in title for 2.8.1 change log.
> Removing extraneous space

- README.md
This was removed in a recent commit by accident I believe
> Add back badge for myget

- README.md
Changing from Open-XML-SDK to Open XML SDK
> Remove extra hyphens in title

- rules.ruleset
- test/DocumentFormat.OpenXml.Tests/ConformanceTest/ChartTrackingRefBased/GeneratedDocument.cs
- test/DocumentFormat.OpenXml.Tests/ConformanceTest/CommentEx/GeneratedDocument.cs
- test/DocumentFormat.OpenXml.Tests/ConformanceTest/CommentExPeople/GeneratedDocument.cs
- test/DocumentFormat.OpenXml.Tests/ConformanceTest/ContentControl/GeneratedDocument.cs
- test/DocumentFormat.OpenXml.Tests/ConformanceTest/FootnoteColumns/GeneratedDocument.cs
- test/DocumentFormat.OpenXml.Tests/ConformanceTest/Guide/GeneratedDocument.cs
- test/DocumentFormat.OpenXml.Tests/ConformanceTest/Pivot/ConnectionGeneratedDocument.cs
- test/DocumentFormat.OpenXml.Tests/ConformanceTest/PresetTransition/GeneratedDocument.cs
- test/DocumentFormat.OpenXml.Tests/ConformanceTest/Slicer/GeneratedDocument.cs
- test/DocumentFormat.OpenXml.Tests/ConformanceTest/Theme/GeneratedDocument.cs
- test/DocumentFormat.OpenXml.Tests/ConformanceTest/ThreadingInfo/GeneratedDocument.cs
- test/DocumentFormat.OpenXml.Tests/ConformanceTest/Timeline/GeneratedDocument.cs
- test/DocumentFormat.OpenXml.Tests/ConformanceTest/WebExtension/WebExtensionData.cs
- test/DocumentFormat.OpenXml.Tests/ConformanceTest/WorkbookPr/GeneratedDocument.cs
- test/DocumentFormat.OpenXml.Tests/GeneratedCode001-Complex-DOCX.cs
- test/DocumentFormat.OpenXml.Tests/GeneratedCode002-Complex-XLSX.cs
- test/DocumentFormat.OpenXml.Tests/GeneratedCode003-Data-Bound-Content-Controls.cs
- test/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/GenerateList4LowLevelTest.cs
- test/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/OpenXmlSimpleValueTest.cs
- test/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/SimpleTypeTest.cs
- test/DocumentFormat.OpenXml.Tests/TestDocx01.cs
- test/DocumentFormat.OpenXml.Tests/TestPptx01.cs
- test/DocumentFormat.OpenXml.Tests/ofapiTest/ListValueTest.cs
- test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlElementTest.cs
- test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlPackageTest.cs
- test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlSimpleValueTest2.cs
- test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlValidatorTest.cs
> Use literal suffix instead of casting

- rules.ruleset
- test/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/CodeGenSanityTest.cs
- test/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/OpenXmlDomTestBase.cs
> Enable SA1136 enum on separate lines

- CHANGELOG.md
- src/DocumentFormat.OpenXml/DocumentFormat.OpenXml.csproj
> Update System.IO.Packaging to 4.5.0

- src/DocumentFormat.OpenXml/Packaging/OpenXmlBasePart.cs
This implements the change suggested [here](https://github.com/OfficeDev/Open-XML-SDK/issues/511#issue-336838389). The issue looked dormant and easy to fix.
> Edit OpenXmlBasePart property comment (fixes #511)

- src/DocumentFormat.OpenXml/Packaging/OpenXmlBasePart.cs
Cherry picked over from feature/Office2016 (81776c9)
Documentation correction.
> Edit OpenXmlBasePart property comment (fixes #511) (#528)

- CHANGELOG.md
> Add change notes for 2.9.1

- src/DocumentFormat.OpenXml/OpenXmlCompositeElement.cs
- src/DocumentFormat.OpenXml/Resources/ExceptionMessages.Designer.cs
- src/DocumentFormat.OpenXml/Resources/ExceptionMessages.resx
> Add better docs and exception message to InsertBefore/InsertAfter

- build/azure-pipelines.yml
- build/nuget.yml
- build/sign.yml
- src/DocumentFormat.OpenXml/DocumentFormat.OpenXml.csproj
> Publish symbol package

- rules.ruleset
> Enable final StyleCop maintainability rules

- Directory.Build.props
- README.md
> Explain ProjectLoadStyle

- Open-XML-SDK.yml
- README.md
I made the following changes:
- Removed YAML metadata from readme
- Updated YAML file with the metadata info
These changes allow us to automatically update the Office gallery (https://developer.microsoft.com/en-us/office/gallery) with information for this tool. This means whenever this tool is referenced in the Office Developer Portals, the user will be seeing the most up-to-date information.
> Gallery automation updates

- CHANGELOG.md
- src/DocumentFormat.OpenXml/OpenXmlElement.cs
- test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlElementTest.cs
> Ensure attributes are initialized when OpenXmlElement is created from outer XML

- src/DocumentFormat.OpenXml/GeneratedCode/schemas-microsoft-com_office_excel.g.cs
Fix for documentation term with update in schema generator.
> East Asia is better term

- CHANGELOG.md
- src/DocumentFormat.OpenXml/Framework/ElementLookup.cs
- src/DocumentFormat.OpenXml/OpenXmlCompositeElement.cs
- test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlCompositeElementTest.cs
> Assume known elements have a high sequence number when comparing elements

- CHANGELOG.md
- src/DocumentFormat.OpenXml/GeneratedCode/schemas_openxmlformats_org_wordprocessingml_2006_main.g.cs
> Add missing values to `CompatSettingNameValues`

- CHANGELOG.md
- src/DocumentFormat.OpenXml/Packaging/OpenXmlPartContainer.cs
- test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlPartTest.cs
> Alter DeletePartCore to use TryGetPartById

- test/DocumentFormat.OpenXml.Benchmarks/ElementMetadataTests.cs
https://github.com/OfficeDev/Open-XML-SDK/pull/758#issuecomment-658772892
> Add Benchmark for create metadata

- src/DocumentFormat.OpenXml/OpenXmlCompositeElement.cs
OpenXmlCompositElement -> OpenXmlCompositeElement
> Fix comment typo

- src/DocumentFormat.OpenXml/Validation/OpenXmlValidator.cs
> Make element validator cancellation token use default

- README.md
Still actively working on this project but there is working code available.
> Add DocxToSource to the list of Related Tools in the README.md file.

- src/DocumentFormat.OpenXml/Spreadsheet/CellValue.cs
- test/DocumentFormat.OpenXml.Tests/Spreadsheet/CellTests.cs
- test/DocumentFormat.OpenXml.Tests/Spreadsheet/CellValueTests.cs
> Allow 0/1 for boolean cell values

- src/DocumentFormat.OpenXml/Framework/OpenXmlNamespace.cs
- src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_drawing_2016_11_diagram.g.cs
- src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_drawing_2016_12_diagram.g.cs
- src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_drawing_2016_SVG_main.g.cs
- src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_drawing_2016_ink.g.cs
- src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_drawing_2017_03_chart.g.cs
- src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_drawing_2018_hyperlinkcolor.g.cs
- src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_powerpoint_2017_3_main.g.cs
- src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_spreadsheetml_2016_pivotdefaultlayout.g.cs
- src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_spreadsheetml_2016_revision5.g.cs
- src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_spreadsheetml_2017_dynamicarray.g.cs
- src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_spreadsheetml_2017_richdata.g.cs
- src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_spreadsheetml_2017_richdata2.g.cs
- src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_spreadsheetml_2018_calcfeatures.g.cs
- src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_word_2016_wordml_cid.g.cs
- test/DocumentFormat.OpenXml.Framework.Tests/ElementChildren.json
- test/DocumentFormat.OpenXml.Framework.Tests/OpenXmlNamespaceTests.cs
- test/DocumentFormat.OpenXml.Packaging.Tests/data/Particles.json
* This commit adds support for the Office 2019 file format types, elements and attributes.
> Office 2019 Updates (#882)

- src/DocumentFormat.OpenXml/Spreadsheet/CellValue.cs
For #903, changing CellValue ctor for double and decimal to use CultureInfo.InvariantCulture.
> CellValue ctor with CultureInfo.InvariantCulture

- src/DocumentFormat.OpenXml/FileFormatVersions.cs
Represents Microsoft Office 2019 comment for Office2019
> Update comment text for FileFormatVersions.cs

- src/DocumentFormat.OpenXml/Packaging/OpenXmlPartContainer.cs
Updates of existing dictionary keys during enumeration are only allowed after net 5.0.
Before that we need a temporary dictionary to store the updated values for the keys.
Intentionally duplicates some parts of the implementation to make both
versions easier to read.
> Implement optimized version to update data parts

- src/DocumentFormat.OpenXml/Packaging/PartDictionary.cs
.NET 5+ allows for removing items while enumerating, while before that
it would fail. This change fixes an error with that, as well as more
lazily loads required fields.
> Fix enumeration error in PartDictionary

- Open-XML-SDK.sln
- samples/AnimatedModel3DExample/Program.cs
- samples/DocumentTaskExample/Program.cs
- samples/DocumentTaskExample/User.cs
- samples/SVGExample/Program.cs
This adds the samples to the solution.
> Add Examples to solution

- Open-XML-SDK.sln
- samples/PowerPointModernCommentSample/PowerPointModernCommentSample.csproj
- samples/PowerPointModernCommentSample/Program.cs
- samples/PowerPointModernCommentSample/Properties/launchSettings.json
- samples/common/PowerPointUtils.cs
The PR adds a sample project showing how to add a PowerPoint modern comment to a slide.
> Powerpoint comment sample

- data/schemas/schemas_microsoft_com_office_drawing_2014_chartex.json
- data/typed/schemas_microsoft_com_office_drawing_2014_chartex.json
- test/DocumentFormat.OpenXml.Framework.Tests/ElementChildren.json
- test/DocumentFormat.OpenXml.Packaging.Tests/data/Particles.json
> pull in chartex.xsd changes since O19

- src/DocumentFormat.OpenXml/Packaging/OpenXmlPartContainer.cs
This relationship type comes from potentially legacy recovered files
> special case relationships/recovered types

- Open-XML-SDK.sln
- data/parts/RdRichValueWebImagePart.json
- samples/RichData/Program.cs
- samples/RichData/Properties/launchSettings.json
- samples/RichData/README.md
- samples/RichData/RichData.csproj
- test/DocumentFormat.OpenXml.Packaging.Tests/data/PartConstraintData.json
- Fixes incorrect casing for rdRichValueWebImage part TargetName and TargetPath
- Adds sample for adding RichData to a spreadsheet
> Add RichData sample and fix casing for rdRichValueWebImage

- Directory.Build.props
- samples/Linq/SvgExample/SvgExampleLinq.csproj
- samples/SVGExample/SVGExample.csproj
Update SVG package to fix [CVE-2021-26701](https://github.com/advisories/GHSA-ghhp-997w-qr28)
> Update SVG package to fix

- Directory.Build.props
- src/Directory.Build.props
- src/DocumentFormat.OpenXml/SimpleTypes/EnumInfoLookup.cs
- src/DocumentFormat.OpenXml/SimpleTypes/EnumValue.cs
> Enable trimming

- Directory.Packages.props
responding to a vulnerability in NewtonSoft 13.0.1
> GHSA-5crp-9r3c-p9vr in Newtonsoft.Json 13.0.1

- samples/SunburstChartExample/Program.cs
- src/DocumentFormat.OpenXml/OpenXmlUnknownElement.cs
- src/DocumentFormat.OpenXml/OpenXmlUnknownElementExtensions.cs
- test/DocumentFormat.OpenXml.Tests/ConformanceTest/Pivot/ConnectionGeneratedDocument.cs
- test/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/GenerateList4LowLevelTest.cs
- test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlCompositeElementTest.cs
- test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlElementTest.cs
- test/DocumentFormat.OpenXml.Tests/ofapiTest/UnknownElementTests.cs
We need access to namespace information, which is most reliably retrieved from a part container.
> Obsolete static unknown element factory

- CHANGELOG.md
- src/DocumentFormat.OpenXml.Framework/SimpleTypes/OpenXmlSimpleType.cs
> Make OpenXmlSimpleType.TextValue private protected

- CHANGELOG.md
- src/DocumentFormat.OpenXml/SimpleTypes/Base64BinaryValue.cs
- src/DocumentFormat.OpenXml/SimpleTypes/HexBinaryValue.cs
- src/DocumentFormat.OpenXml/SimpleTypes/ListValue.cs
- src/DocumentFormat.OpenXml/SimpleTypes/OpenXmlSimpleType.cs
- src/DocumentFormat.OpenXml/SimpleTypes/OpenXmlSimpleValue.cs
- src/DocumentFormat.OpenXml/SimpleTypes/StringValue.cs
> Mark OpenXmlSimpleType.TextValue as obsolete

- src/DocumentFormat.OpenXml/Features/IDocumentTypeFeature.cs
> Make IDocumentTypeFeature public

- CHANGELOG.md
- src/DocumentFormat.OpenXml/Packaging/DataPart.cs
- src/DocumentFormat.OpenXml/Packaging/OpenXmlPackage.FlatOpc.cs
- src/DocumentFormat.OpenXml/Packaging/OpenXmlPackage.cs
- src/DocumentFormat.OpenXml/Packaging/OpenXmlPart.cs
- src/DocumentFormat.OpenXml/Packaging/OpenXmlPartContainer.cs
- src/DocumentFormat.OpenXml/Packaging/PackagePartUriHelper.cs
- test/DocumentFormat.OpenXml.Tests/ConformanceTest/General/ConformanceTestBase.cs
- test/DocumentFormat.OpenXml.Tests/SaveAndCloneTests.cs
- test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlPackageTest.cs
- Obsolete OpenXmlPackage.Package
Fixes #1299
> Obsolete OpenXmlPackage.Package

- src/DocumentFormat.OpenXml/Packaging/OpenXmlPart.cs
- test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlPartTest.cs
> Use correct file extensions with inserted files

- Directory.Packages.props
> Update System.IO.Packaging to 7.0.0

- gen/DocumentFormat.OpenXml.Generator.Models/Editor/TextWriterExtensions.cs
- gen/DocumentFormat.OpenXml.Generator.Models/Generators/Linq/LinqGeneratorExtensions.cs
- gen/DocumentFormat.OpenXml.Generator.Models/OpenXmlGeneratorDataSource.cs
- gen/DocumentFormat.OpenXml.Generator.Models/OpenXmlGeneratorServices.cs
- gen/DocumentFormat.OpenXml.Generator/FactoryGenerator.cs
- gen/DocumentFormat.OpenXml.Generator/GeneratorExtensions.cs
- gen/DocumentFormat.OpenXml.Generator/IFeatureImplementationBuilder.cs
- gen/DocumentFormat.OpenXml.Generator/OpenXmlGenerator.cs
- gen/DocumentFormat.OpenXml.Generator/OpenXmlGeneratorContext.cs
- gen/DocumentFormat.OpenXml.Generator/PackageGeneratorExtensions.cs
- gen/DocumentFormat.OpenXml.Generator/PartGenerator.cs
- gen/DocumentFormat.OpenXml.Generator/Properties/launchSettings.json
- gen/DocumentFormat.OpenXml.Generator/RoslynExtensions.cs
- generated/DocumentFormat.OpenXml.Framework/DocumentFormat.OpenXml.Generator/DocumentFormat.OpenXml.Generator.OpenXmlGenerator/Attributes.g.cs
- generated/DocumentFormat.OpenXml.Linq/DocumentFormat.OpenXml.Generator/DocumentFormat.OpenXml.Generator.OpenXmlGenerator/Attributes.g.cs
- generated/DocumentFormat.OpenXml/DocumentFormat.OpenXml.Generator/DocumentFormat.OpenXml.Generator.OpenXmlGenerator/Attributes.g.cs
- generated/DocumentFormat.OpenXml/DocumentFormat.OpenXml.Generator/DocumentFormat.OpenXml.Generator.OpenXmlGenerator/Package_PresentationDocument.cs
- generated/DocumentFormat.OpenXml/DocumentFormat.OpenXml.Generator/DocumentFormat.OpenXml.Generator.OpenXmlGenerator/Package_SpreadsheetDocument.cs
- generated/DocumentFormat.OpenXml/DocumentFormat.OpenXml.Generator/DocumentFormat.OpenXml.Generator.OpenXmlGenerator/Package_WordprocessingDocument.cs
- src/DocumentFormat.OpenXml/DocumentFormat.OpenXml.csproj
- src/DocumentFormat.OpenXml/Packaging/PresentationDocument.cs
- src/DocumentFormat.OpenXml/Packaging/SpreadsheetDocument.cs
- src/DocumentFormat.OpenXml/Packaging/WordprocessingDocument.cs
This should help with starting to decompose all of the package/parts/schemas to just what is necessary by letting us annotate things with attributes.
> Refactor part of generator to be triggered from attribute

- src/DocumentFormat.OpenXml/Packaging/ImagePartExtensions.cs
- src/DocumentFormat.OpenXml/Packaging/ImagePartTypeInfo.cs
> Add mime types to GetImagePartType extension method

- .github/workflows/aot.yml
- .github/workflows/benchmarks.yml
These appear to be on the way to being deprecated and are out of date
anyway
> Update to latest checkout and build actions

- src/DocumentFormat.OpenXml.Features/TypedForwards.cs
- src/DocumentFormat.OpenXml.Framework/ExperimentalApis.cs
> Update main from release/v3.0.0

- src/DocumentFormat.OpenXml.Framework/Validation/PackageValidator.cs
- test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlValidatorTest.cs
> Fix PackageStructureValidatingTest

- CHANGELOG.md
This change also collapses the beta changes now that we've passed them so they make more sense for people who are just looking at supported changes
> Update changelog for 3.0.1

- Directory.Build.props
- closes #1666 
- closes #1664
> Add nuget readme to DocumentFormat.OpenXml and DocumentFramework.OpenXml.Framework

- src/DocumentFormat.OpenXml.Framework/Packaging/WriteableStreamExtensions.cs
> Ensure temp files are non-shareable and delete on close

- .github/ISSUE_TEMPLATE/documentation_request.md
> Add a request for documentation when creating an issue

- src/DocumentFormat.OpenXml.Framework/Resources/ExceptionMessages.Designer.cs
- src/DocumentFormat.OpenXml.Framework/Resources/ExceptionMessages.resx
- src/DocumentFormat.OpenXml/Packaging/TypedPackageFeatureCollection.cs
- test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlPackageTest.cs
> Use default document type if no main part is available

- src/DocumentFormat.OpenXml.Framework/Packaging/OpenXmlPackage.cs
> Update docs that Dispose does not save the content if AutoSave property is false

- data/parts/RdRichValueWebImagePart.json
- generated/DocumentFormat.OpenXml/DocumentFormat.OpenXml.Generator/DocumentFormat.OpenXml.Generator.OpenXmlGenerator/Part_RdRichValueWebImagePart.g.cs
- generated/DocumentFormat.OpenXml/DocumentFormat.OpenXml.Generator/DocumentFormat.OpenXml.Generator.OpenXmlGenerator/Part_WorkbookPart.g.cs
- test/DocumentFormat.OpenXml.Packaging.Tests/data/PartConstraintData.json
> fixes issue1758 rdRichValueWebImage part
