dotnet/Open-XML-SDK

DocumentFormat.OpenXml/src/ofapi/Validation/SemanticValidation/SemanticConstraint/SemanticConstraint.cs
Attribute strings containing decimal numbers were not correctly converted to double for all cultures. This commit fixes that issue.
See #49 for details.
=> Fix SemanticConstraint.GetAttrNumVal method

DocumentFormat.OpenXml.Tests/TestFileStreams.resx, DocumentFormat.OpenXml.WB.Tests/TestFileStreams.resx
I tried to build the unit tests on a Linux VM, and got a compile error due to cases sensitivity issues in the test file names (e.g. one of the test files is called 'May 12 04.docx', but the .resx file includes 'may 12 04.docx').
Not an issue on Windows of course, so this change should get it to build on Linux without effecting that.
=> fix case sensitivity issue in tests

DocumentFormat.OpenXml/src/Framework/OpenXmlCompositeElement.cs, DocumentFormat.OpenXml/src/Framework/OpenXmlElement.cs, DocumentFormat.OpenXml/src/Framework/OpenXmlLeafTextElement.cs, DocumentFormat.OpenXml/src/Framework/OpenXmlNonElementNode.cs, DocumentFormat.OpenXml/src/Framework/OpenXmlReader.cs, DocumentFormat.OpenXml/src/Framework/XmlDOMTextWriter.cs
.NET Standard does not expose XmlTextWriter, so this change mimics the
behavior of deriving from XmlWriter instead of XmlTextWriter
This is a part of #111
@tomjebo
=> Update XmlDOMTextWriter to derive from XmlWriter

DocumentFormat.OpenXml/src/Framework/OpenXmlPackage.cs, DocumentFormat.OpenXml/src/Framework/PartContainer.cs
This replaces `CollectionBase` and `StringCollection` with supported equivalents that are supported in .NET Standard.
This is part of issue #111
@tomjebo
=> Replace a couple APIs not supported in .NET Standard

DocumentFormat.OpenXml/src/ofapi/Validation/SchemaValidation/BinarySdbSchemaDatas.cs, DocumentFormat.OpenXml/src/ofapi/Validation/SchemaValidation/SdbSchemaDatas.cs
The current schema validation utilizes a database that is read with BinaryFormatter. This change is the first of a process to remove the need to use BinaryFormatter by separating out the necessary part of the SbdSchemaDatas from what is solely required for the binary database.
=> Abstract binary formatter schema validation

DocumentFormat.OpenXml.Tests/OpenXmlDomTest/SimpleTypeTest.cs, DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlSimpleValueTest2.cs
Added CultureInfo.InvariantCulture parameter to several locations in
order to fix the following tests where using a decimal separater other
than a period was causing failures. Fixes #91.
OpenXmlSimpleValueTest.DecimalValueTest
OpenXmlSimpleValueTest.DoubleValueTest
OpenXmlSimpleValueTest.SingleValueTest
OpenXmlSimpleValueTest2.SingleValueTest
=> Bug fixes for issue #91

DocumentFormat.OpenXml.Tests/OpenXmlDomTest/SimpleTypeTest.cs, DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlSimpleValueTest2.cs
Reverts OfficeDev/Open-XML-SDK#141
backing out this PR to get strong naming in under the 2.7 tag.
=> Revert "Bug fixes for issue #91"

DocumentFormat.OpenXml.Tests/project.json, DocumentFormat.OpenXml/src/Framework/MediaDataPart.cs
Reverts OfficeDev/Open-XML-SDK#141
backing out this PR to get strong naming in under the 2.7 tag.
=> Revert "Issue #84"

DocumentFormat.OpenXml/src/ofapi/Validation/SchemaValidation/SimpleTypes.cs, README.md
The binary file was created with a 2.6.0 version of the library with no strong name. If Validate is called without this fix, there is a deserialization exception that will cause a crash. By redirecting the binding, we can force the deserialization to load internal types from the current instance of the assembly and don't need to worry about any later version causing a binding failure.
Fixes #159
=> Fix binary formatter to deserialize internal types correctly

appveyor.yml, build/SignPackage.ps1
The symbols are too large to push to myget so we are disabling them. There
is currently no option to exclude symbol package generation, so we will
manually do it in the sign script. This is fixed in preview4 of the tooling
and should simplify the sign script.
@tomjebo
=> Exclude symbols from signing and artifacts

DocumentFormat.OpenXml.Tests/OpenXmlDomTest/GenerateList4LowLevelTest.cs, DocumentFormat.OpenXml.Tests/OpenXmlDomTest/OpenXmlCompositeElementTestClass.cs
The folder that the test files are in is called 'bugregression', but the tests refer to it as 'BugRegression'. This causes it to fail to find the files on Linux.
=> Case sensitive path issue: BugRegression -> bugregression

DocumentFormat.OpenXml.Tests/OpenXmlDomTaskLibrary/DataStorage/TestDataStorage.cs, DocumentFormat.OpenXml.Tests/OpenXmlDomTaskLibrary/TestScripts/OpenXmlTestBase.cs, DocumentFormat.OpenXml.Tests/OpenXmlDomTest/DocumentTraverseTest.cs, DocumentFormat.OpenXml.Tests/OpenXmlDomTest/OpenXmlCompositeElementTestClass.cs, DocumentFormat.OpenXml.Tests/OpenXmlDomTest/OpenXmlReaderWriterTest.cs
These changes try to fix some hard coded path separators in the tests that cause failures on non-Windows platforms (Linux/OSX).
I only have a Linux dev setup to hand at the moment, so I hope this is ok.
=> fix hard coded path separators in tests

DocumentFormat.OpenXml/src/Framework/DataPartReferenceRelationship.cs, DocumentFormat.OpenXml/src/Framework/MediaDataPart.cs, DocumentFormat.OpenXml/src/Framework/NamespaceIdMap.cs, DocumentFormat.OpenXml/src/Framework/OpenXmlAttribute.cs, DocumentFormat.OpenXml/src/Framework/OpenXmlBasePart.cs, DocumentFormat.OpenXml/src/Framework/OpenXmlCompositeElement.cs, DocumentFormat.OpenXml/src/Framework/OpenXmlElement.cs, DocumentFormat.OpenXml/src/Framework/OpenXmlElementList.cs, DocumentFormat.OpenXml/src/Framework/OpenXmlNonElementNode.cs, DocumentFormat.OpenXml/src/Framework/OpenXmlPackage.cs, DocumentFormat.OpenXml/src/Framework/OpenXmlPartRootElement.cs, DocumentFormat.OpenXml/src/Framework/OpenXmlReader.cs, DocumentFormat.OpenXml/src/Framework/OpenXmlSimpleType.cs, DocumentFormat.OpenXml/src/Framework/OpenXmlUnknownElement.cs, DocumentFormat.OpenXml/src/Framework/OpenXmlWriter.cs, DocumentFormat.OpenXml/src/Framework/PartContainer.cs, DocumentFormat.OpenXml/src/Framework/PartExtensionProvider.cs, DocumentFormat.OpenXml/src/Framework/UnknownPart.cs, DocumentFormat.OpenXml/src/Framework/XmlDOMTextWriter.cs, DocumentFormat.OpenXml/src/ofapi/BinaryTypeEnums.cs, DocumentFormat.OpenXml/src/ofapi/ExtensionMethods.cs, DocumentFormat.OpenXml/src/ofapi/HelperPartialClass.cs, DocumentFormat.OpenXml/src/ofapi/PackageDocument.cs, DocumentFormat.OpenXml/src/ofapi/SchemaInfoAttribute.cs, DocumentFormat.OpenXml/src/ofapi/Sources1.cs, DocumentFormat.OpenXml/src/ofapi/Validation/OpenXmlValidator.cs, DocumentFormat.OpenXml/src/ofapi/Validation/SchemaValidation/BinDataTypes.cs, DocumentFormat.OpenXml/src/ofapi/Validation/SchemaValidation/SimpleTypes.cs, DocumentFormat.OpenXml/src/ofapi/Validation/XmlPath.cs
- The changes were done in DocumentFormat.OpenXml project
- Simple replacement for basic scenarios like throwing an exception
- No logic code change
=> Code cleanup - introducing the 'nameof' operator instead of string values

DocumentFormat.OpenXml.Tests/FlatOpcFixture.cs, DocumentFormat.OpenXml.Tests/SaveAndCloneFixture.cs
needed to get the tests to work on OSX
=> Avoid hard coded path separators in the SaveAndClone/FlatOpc tests

DocumentFormat.OpenXml/src/Framework/OpenXmlPackage.cs
Reverted to previous behavior where we use base10 numbering format for parts in the package. closes #169
=> Revert to previous behavior for part numbering.

README.md
We should at least add this change in the instructions. should we also add a note for the VS requirement now?
=> changed 2015 to 2017 for VS build instructions

DocumentFormat.OpenXml.Tests/ConformanceTest/ChartTrackingRefBased/ChartTrackingRefBasedTest.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/CommentEx/CommentExTest.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/CommentExPeople/CommentExPeopleTest.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/ContentControl/ContentControlTest.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/FootnoteColumns/FootnoteColumnTest.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/General/ConformanceTestBase.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/Guide/GuideTest.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/Pivot/PivotTest.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/PresetTransition/PresetTransitionTest.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/Slicer/SlicerTest.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/Theme/ThemeTest.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/ThreadingInfo/ThreadingInfoTest.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/Timeline/TimeLineTest.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/WebExtension/WebExtensionTest.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/WorkbookPr/WorkBookPrTest.cs, DocumentFormat.OpenXml.Tests/IsoStrictTest/IsoStrictTest.cs, DocumentFormat.OpenXml.Tests/OFCatTest/Robustness.cs, DocumentFormat.OpenXml.Tests/OpenXmlDomTaskLibrary/TestScripts/OpenXmlTestBase.cs, DocumentFormat.OpenXml.Tests/OpenXmlDomTest/AutoSaveTestClass.cs, DocumentFormat.OpenXml.Tests/OpenXmlDomTest/CodeGenSanityTest.cs, DocumentFormat.OpenXml.Tests/OpenXmlDomTest/DocumentTraverseTest.cs, DocumentFormat.OpenXml.Tests/OpenXmlDomTest/GenerateList4LowLevelTest.cs, DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs, DocumentFormat.OpenXml.Tests/OpenXmlDomTest/OpenXmlCompositeElementTestClass.cs, DocumentFormat.OpenXml.Tests/OpenXmlDomTest/OpenXmlDomTestBase.cs, DocumentFormat.OpenXml.Tests/OpenXmlDomTest/OpenXmlReaderWriterTest.cs, DocumentFormat.OpenXml.Tests/OpenXmlDomTest/OpenXmlRootElementTestClass.cs, DocumentFormat.OpenXml.Tests/OpenXmlDomTest/SimpleTypeTest.cs, DocumentFormat.OpenXml.Tests/ofapiTest/BugRegressionTest.cs
Xunit will construct a new instance of the object for each test run, so
initialization code should be done in the constructor. This helps clean
up a ton of hard-to-reason about code.
=> Remove test initializer infrastructure

README.md
Fixed minor typo on link to https://github.com/OfficeDev/Open-Xml-PowerTools
=> Fixed minor typo on link to Open-Xml-PowerTools

DocumentFormat.OpenXml.Tests/ConformanceTest/ChartTrackingRefBased/GeneratedDocument.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/CommentEx/GeneratedDocument.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/CommentExPeople/GeneratedDocument.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/ContentControl/GeneratedDocument.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/FootnoteColumns/GeneratedDocument.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/Guide/GeneratedDocument.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/Pivot/ConnectionGeneratedDocument.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/PresetTransition/GeneratedDocument.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/Slicer/GeneratedDocument.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/Theme/GeneratedDocument.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/ThreadingInfo/GeneratedDocument.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/Timeline/GeneratedDocument.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/Timeline/TimeLineTest.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/WebExtension/WebExtensionData.cs, DocumentFormat.OpenXml.Tests/ConformanceTest/WorkbookPr/GeneratedDocument.cs, DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlValidatorTest.cs, rules.ruleset
GIT and many other tools work best with UTF8+BOM encoding. Most files in the repo were encoded as such, but a few weren't. This enables StyleCop to check for the encoding, and updates those files that aren't encoded correctly. Part of #197
=> Ensure all files are UTF8 with BOM

DocumentFormat.OpenXml.Tests/DocumentFormat.OpenXml.Tests.csproj, DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs, Open-XML-SDK.sln
This change fixes the test cases that take the most amount of time, shaving about 30% of the unit test duration. Subsequent PRs will address the rest.
=> Refactor initial markup compatibility tests to decrease unit test duration

DocumentFormat.OpenXml.Tests/SaveAndCloneTests.cs, DocumentFormat.OpenXml/src/Framework/OpenXmlPackage.cs
Currently, if a document is opened with `AutoSave = false`, then calls to `.Save()` will fail. This change allows packages that are opened with `AutoSave = false` to be manually saved if desired, while maintaining previous behavior when `AutoSave = true`.
Fixes #262
=> Allow saving when autosave is false

DocumentFormat.OpenXml/src/Framework/OpenXmlPackage.cs, DocumentFormat.OpenXml/src/PortabilityExtensions.cs, DocumentFormat.OpenXml/src/ofapi/PackageDocument.cs, DocumentFormat.OpenXml/src/ofapi/Validation/SchemaValidation/SimpleTypes.cs
In .NET new Uri ("/foo", UriKind.RelativeOrAbsolute) returns a relative
Uri whereas Mono assumes it is an absolute file path.
Mono diverges from .NET because UNIX file paths starting with
'/' are absolute file paths.
This change introduces a UriHelper class that provides a workaround by
redefining RelativeOrAbsolute to a Mono specific value when on that
platform.
For more information, see:
www.mono-project.com/docs/faq/known-issues/urikind-relativeorabsolute/
Fixes #249, #221, #59
=> Use a UriKind.RelativeOrAbsolute wrapper for Mono support

DocumentFormat.OpenXml/FileFormatVersions.cs, DocumentFormat.OpenXml/OfficeAvailabilityAttribute.cs, DocumentFormat.OpenXml/OfficeVersions.cs, DocumentFormat.OpenXml/src/Framework/AlternateContent.cs, DocumentFormat.OpenXml/src/Framework/OpenXmlElementContext.cs, DocumentFormat.OpenXml/src/ofapi/PackageDocument.cs
This adds an extension method to expand a given version to include itself and all alter versions. This helps to clean up some code so it is clearer conceptually what is going on and to minimize any code churn between the vNext branch and the Office2016 branch.
=> Add an extension method to expand FileFormatVersion to include all alter versions

Directory.Build.props, DocumentFormat.OpenXml.Tests/DocumentFormat.OpenXml.Tests.csproj, DocumentFormat.OpenXml/DocumentFormat.OpenXml.csproj, appveyor.yml
This makes it so when loading in VS, it will by default only load the .NET Standard/.NET Core version. Environment variables may be used to load others. This is because VS gets unstable sometimes with the default configuration. The CI builds will continue to build for all combinations and include tests for them all.
=> Add customizable property to only build for certain targets

Directory.Build.targets, README.md, appveyor.yml, rules.ruleset
This adds the new FxCop analyzers that are supported in 15.5. This change adds the analyzers but disables all failing rules, which can be enabled in future PRs.
=> Add FxCop analyzers

CHANGELOG.md, DocumentFormat.OpenXml.Package.props, README.md
@tomjebo Here's some of that "MSBuild magic" to keep a single changelog instead of multiple.
=> Keep a single centralized changelog

CHANGELOG.md
This was fixed in #312 and released with 2.8.0, but didn't make it into the change log
=> Add UTF8 without BOM to changelog

DocumentFormat.OpenXml/SimpleTypes/ListValue.cs, DocumentFormat.OpenXml/SimpleTypes/OpenXmlSimpleType.cs, DocumentFormat.OpenXml/Validation/Schema/Restrictions/ListValueRestriction.cs
`OpenXmlSimpleType` only has a single implementation that needs list access, so this switches it to use an interface implementation rather than an abstract method.
=> Add IEnumerable<T> to ListValue

src/DocumentFormat.OpenXml/SimpleTypes/EnumStringAttribute.cs, src/DocumentFormat.OpenXml/SimpleTypes/EnumStringLookup.cs, src/DocumentFormat.OpenXml/SimpleTypes/EnumValue.cs, src/DocumentFormat.OpenXml/SimpleTypes/OpenXmlSimpleValue.cs, test/DocumentFormat.OpenXml.Tests/SimpleTypes/EnumStringLookupTests.cs, test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlSimpleValueTest2.cs
The current parsing logic has a caching mechanism that duplicates a lot of code and allocates a number of unneeded objects. This cleans up the parsing mechanism to cache at the onset with minimal allocations. By moving to its own type (EnumStringLookup), the EnumValue itself can more easily inherit from OpenXmlValueType and get a lot of the error checking for free.
=> Simplify enum parsing utilities

src/DocumentFormat.OpenXml/Packaging/OpenXmlPackage.cs, src/DocumentFormat.OpenXml/Packaging/OpenXmlPackageValidationEventArgs.cs, src/DocumentFormat.OpenXml/Packaging/OpenXmlPartContainer.cs, src/DocumentFormat.OpenXml/Validation/DocumentValidator.cs, src/DocumentFormat.OpenXml/Validation/PackageValidator.cs, src/DocumentFormat.OpenXml/Validation/ValidationErrorInfo.cs
The current validation logic uses obsolete APIs. This is the first step to update to the newer validation system by extracting the validation information from OpenXmlContainer
=> Extract validator from OpenXmlContainer

src/DocumentFormat.OpenXml/FileFormatVersionExtensions.cs, src/DocumentFormat.OpenXml/Packaging/PartConstraintRule.cs, src/DocumentFormat.OpenXml/Validation/PackageValidator.cs, test/DocumentFormat.OpenXml.Packaging.Tests/PartConstraintRuleTests.cs, test/DocumentFormat.OpenXml.Packaging.Tests/data/PartConstraintData.json, test/DocumentFormat.OpenXml.Tests/FileFormatVersionExtensionsTests.cs
This allows us to just query `FileFormatVersions.AtLeast` to check if a value is valid. This simplifies merge issues and makes it clearer what the minimum version is.
=> Just store the initial office version

src/DocumentFormat.OpenXml/Packaging/PartExtensionProvider.cs, test/DocumentFormat.OpenXml.Packaging.Tests/PartExtensionProviderTests.cs
This also fixes the case where a content type already exists and a new part extension is added.
=> Add tests for part extension provider

src/DocumentFormat.OpenXml/GeneratedCode/PartParitalDef.g.cs, src/DocumentFormat.OpenXml/Packaging/CustomUIPart.cs, src/DocumentFormat.OpenXml/Packaging/MailMergeRecipientDataPart.cs, src/DocumentFormat.OpenXml/Packaging/OpenXmlBasePart.cs, src/DocumentFormat.OpenXml/Packaging/StylesPart.cs
- Uses `private protected` for `_rootElement`
- Renames `_metroPackage` to `_package`
=> Organize fields in OpenXmlBasePart

src/DocumentFormat.OpenXml/Packaging/ExtendedPart.cs, src/DocumentFormat.OpenXml/Packaging/OpenXmlBasePart.cs, src/DocumentFormat.OpenXml/Packaging/OpenXmlPackage.cs, src/DocumentFormat.OpenXml/Packaging/OpenXmlPartContainer.cs, src/DocumentFormat.OpenXml/Validation/PackageValidator.cs, test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlPartTest.cs
There are two properties that point to the same instance of data. This also obsoletes a couple of methods that are redundant with simple LINQ operators that we don't need to maintain in the long run. With the next major version, we'll remove them, but for now they are marked with the ObsoleteAttribute.
=> Use single property for OpenXmlPackage.ChildrenParts and PartDictionary

src/DocumentFormat.OpenXml/OpenXmlElementContext.cs, test/DocumentFormat.OpenXml.Tests/OpenXmlElementContextTests.cs
This fixes up OpenXmlElementContext in a few ways:
- Initializes things on a path such that items can be marked as readonly
- Removes custom event handling to default to compiler generated one. The current one is not thread safe and provides no benefit over the default one
- Adds unit tests to cover various aspects of the context
=> Streamline OpenXmlElementContext initialization

NuGet.Config, Open-XML-SDK.sln
Visual Studio seems to be adding this automatically and will make it easier to potentially add other sources in the future.
=> Add default NuGet.config

appveyor.yml
Compat analyzer is currently down so disabling for now
=> Ignore compat while system is down

CHANGELOG.md, Directory.Build.props, Directory.Build.targets, Open-XML-SDK.sln, src/DocumentFormat.OpenXml/DocumentFormat.OpenXml.csproj
According to the documentation (https://docs.microsoft.com/en-us/dotnet/standard/net-standard), it is recommended that even if we target .NET Standard 1.3, we should also provide a .NET Standard 2.0 build as well. This will minimize the dependency graph required by consumers.
With this change, tests for .NET Standard 1.3 are run on the .NET Core 1.x builds while those for .NET Standard 2.0 are run on .NET Core 2.1.
=> Add .NET Standard 2.0 support

Directory.Build.props
This commit fixes the Directory.Build.props by:
- adding an Otherwise block for cases where the ProjectLoadStyle variable is not correctly defined and
- renaming DevCore30 to DevCore31 to be consistent with the comment.
Fixes #652.
=> Add fallback for ProjectLoadStyle in Directory.Build.props

CHANGELOG.md, src/DocumentFormat.OpenXml/Packaging/OpenXmlPackage.FlatOpc.cs, src/DocumentFormat.OpenXml/Packaging/PresentationDocument.FlatOpc.cs, src/DocumentFormat.OpenXml/Packaging/SpreadsheetDocument.FlatOpc.cs, src/DocumentFormat.OpenXml/Packaging/WordprocessingDocument.FlatOpc.cs, src/DocumentFormat.OpenXml/Resources/ExceptionMessages.Designer.cs, src/DocumentFormat.OpenXml/Resources/ExceptionMessages.resx, test/DocumentFormat.OpenXml.Packaging.Tests/OpenXmlPackageTests.cs
This commit enhances the
```XDocument OpenXmlPackage.ToFlatOpcDocument(XProcessingInstruction)```
method to consider "altChunk parts" (AlternativeFormatInputParts),
which must have their content rendered in binary form even if it is XML
content (e.g., XML, XHTML).
Fixes #525.
=> Consider altChunk parts in Flat OPC transformation

src/DocumentFormat.OpenXml/Validation/DocumentValidator.cs, src/DocumentFormat.OpenXml/Validation/ValidationErrorInfo.cs
If any errors are encountered, `ValidationErrorInfo` automatically creates an `Xmlpath` instance. However, this is somewhat expensive to create and may not be used. The validation perf test on master is this:
| Method     | Mean     | Error   | StdDev  | Gen 0     | Allocated |
| ---------- | -------- | ------- | ------- | --------- | --------- |
| Before     | 141.8 ms | 2.75 ms | 2.70 ms | 5000.0000 | 23.72 MB  |
| After      | 138.5 ms | 4.55 ms | 4.68 ms | 4000.0000 | 19.87 MB  |
There's a slight reduction in time, but a large reduction in Gen0 and overall allocations (~17%)
=> Lazily create XmlPath in ValidationErrorInfo

CHANGELOG.md, src/DocumentFormat.OpenXml/OpenXmlElementFunctionalExtensions.cs, test/DocumentFormat.OpenXml.Tests/OpenXmlElementFunctionalExtensionsTests.cs
This commit implements the OpenXmlElementFunctionalExtensions class and
related unit tests.
Fixes #634.
=> Implement OpenXmlElementFunctionalExtensions

CHANGELOG.md, src/DocumentFormat.OpenXml/Validation/Schema/ChoiceParticleValidator.cs, src/DocumentFormat.OpenXml/Validation/Schema/CompositeParticleValidator.cs, src/DocumentFormat.OpenXml/Validation/Schema/SequenceParticleValidator.cs
This fixes an issue where it is non-threadsafe to validate the same element type on different threads, even if it were  from different validation runs.
=> Remove state from particle validators

CHANGELOG.md, src/DocumentFormat.OpenXml/OpenXmlElement.cs, src/DocumentFormat.OpenXml/OpenXmlMiscNode.cs, test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlElementTest.cs
Continues #684 for the `OuterXml` property as well as the constructor.
=> Ensure attributes are available when OuterXml property is set

CHANGELOG.md, src/DocumentFormat.OpenXml/DocumentFormat.OpenXml.csproj, test/DocumentFormat.OpenXml.Tests/DocumentFormat.OpenXml.Tests.csproj
Thie excludes OpenXmlElementFunctionalExtensions and tests for 2.10.1 release since that is new surface area not appropriate for a revision release. This will be re-enabled after the revision release. This is to get a couple of fixes out for #684 and #690 that were breaking behavior from 2.10.0
=> Ready for 2.10.1 release

CHANGELOG.md, Directory.Build.props, samples/IsolatedStorageExceptionWorkaround/IsolatedStorageExceptionWorkaround.csproj, src/DocumentFormat.OpenXml/OpenXmlAttribute.cs, test/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/OpenXmlCompositeElementTestClass.cs, test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlElementTest.cs
This change takes advantage of a C# 8.0 features that allows obsolete messages for setters independent of the getter. Since `OpenXmlAttribute` is an attribute, we should remove the setters from it so the attribute becomes immutable. That's a breaking change, so we'll mark it as obsolete, and the next major version will remove it.
=> Add Obsolete to OpenXmlAttribute setters

CHANGELOG.md, src/DocumentFormat.OpenXml/GeneratedCode/schemas-microsoft-com_vml.g.cs, test/DocumentFormat.OpenXml.Tests/TestDocx01.cs
add gfxdata attribue to Arc, Curve, Line, PolyLine, Group, Image, Oval, Rect, and RoundRect shape complex types per MS-OI29500 2.1.1783-1799
Fixes #709
=> Add gfxdata attribute 

CHANGELOG.md, src/DocumentFormat.OpenXml/Packaging/OpenXmlPartContainer.cs
=> Add TryGetPartById

CHANGELOG.md, src/DocumentFormat.OpenXml/OpenXmlElement.cs, src/DocumentFormat.OpenXml/OpenXmlPartRootElement.cs, src/DocumentFormat.OpenXml/Packaging/OpenXmlPackage.cs, src/DocumentFormat.OpenXml/Packaging/RelationshipCollection.cs, src/DocumentFormat.OpenXml/XmlConvertingReader.cs, src/DocumentFormat.OpenXml/XmlConvertingReaderFactory.cs, test/DocumentFormat.OpenXml.Tests/IsoStrictTest/IsoStrictTest.cs, test/DocumentFormat.OpenXml.Tests/XmlConvertingReaderTests.cs, test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlPackageTest.cs
Fixes #711 
This PR firstly renames `StrictTranslation` to `StrictRelationshipFound` and secondly makes the `OpenXmlPackage.StrictRelationshipFound` property public (from internal).
This will provide a hint to subsequent parsers that it may need to support strict mode parsing.
=> Rename StrictTranslation to StrictRelationshipFound and make public

CHANGELOG.md, src/DocumentFormat.OpenXml/Framework/PartConstraintCollection.cs, test/DocumentFormat.OpenXml.Packaging.Tests/PartConstraintCollectionTypes.cs
=> Inherit parts to child parts

CHANGELOG.md, src/DocumentFormat.OpenXml/Validation/Schema/SchemaTypeValidator.cs, src/DocumentFormat.OpenXml/Validation/Semantic/AttributeRequiredConditionToValue.cs, src/DocumentFormat.OpenXml/Validation/ValidationResources.Designer.cs, src/DocumentFormat.OpenXml/Validation/ValidationResources.resx, test/DocumentFormat.OpenXml.Tests/Validation/Semantic/AttributeRequiredConditionToValueTests.cs
The semantic constraint `AttributeRequiredConditionToValue` does not need to be checked if the required value exists. This was causing incorrect semantic validation of the form `Semantic Error : Attribute 'si' should be present when the value of attribute 't' is 'shared'`. Now, if the required value exists, the constraint is exited without looking further as there is no way it could fail.
Fixes #735
=> Skip attribute required semantic check if the required attribute exists

CHANGELOG.md, src/DocumentFormat.OpenXml/Spreadsheet/CellValue.cs, test/DocumentFormat.OpenXml.Tests/SpreadsheetCellTests.cs
Fixes #724 and adds test to ensure that's all that changes
No standard format limits to three digits for milliseconds, but the format is the same as `"o"` used before in all other regards
=> Limit milliseconds to three digits

src/DocumentFormat.OpenXml/Framework/Metadata/ElementLookup.cs
But now there's no code that uses the `Contains` method.
=> Remove unused ElementLookup.Contains method

CHANGELOG.md, src/DocumentFormat.OpenXml/Validation/Semantic/IndexReferenceConstraint.cs, src/DocumentFormat.OpenXml/Validation/Semantic/ReferenceExistConstraint.cs, src/DocumentFormat.OpenXml/Validation/StateManager.cs
This changes `IndexReferenceConstraint` and `ReferenceExistConstraint` to be much more performant. Two issues were found:
- Using validation infrastructure to just iterate through all the children in a part. Fixing this brought the example issue down from 1.5hr to 15 min
- Recalculating same required information many, many times. Caching this brought the time down from 15 min, to 33 seconds
Fixes #760
=> Reduce massive perf impact from a couple semantic constraints

src/DocumentFormat.OpenXml/OpenXmlElement.cs, src/DocumentFormat.OpenXml/Validation/Semantic/IndexReferenceConstraint.cs, src/DocumentFormat.OpenXml/Validation/Semantic/ReferenceExistConstraint.cs, src/DocumentFormat.OpenXml/Validation/Semantic/UniqueAttributeValueConstraint.cs, src/DocumentFormat.OpenXml/Validation/StateManager.cs, src/DocumentFormat.OpenXml/Validation/TraversalOptions.cs, src/DocumentFormat.OpenXml/Validation/ValidationTraverser.cs, test/DocumentFormat.OpenXml.Tests/ofapiTest/BugRegressionTest.cs, test/DocumentFormat.OpenXml.Tests/ofapiTest/SchemaValidatorTest.cs
Update ValidationTraverser to not be recursive. This allows us to stream the elements it finds, including the elements from the correct AlternateContent blocks.
=> Stream children in a validation traversal

CHANGELOG.md, Directory.Build.props, README.md, samples/SunburstChartExample/SunburstChartExample.csproj, src/DocumentFormat.OpenXml/DocumentFormat.OpenXml.csproj
Currently we're using System.IO.Packaging NuGet package on .NET 4.6+,
when this isn't really necessary. This ends up just being a bunch of
type forwarders that people don't really need on .NET Framework. We can
just directly reference WindowsBase instead.
This should be a non-breaking change as all the type-forwarders would be
brought in by another dependency if they require them.
=> Use WindowsBase instead of package on .NET Framework

src/DocumentFormat.OpenXml/AppendOption.cs, src/DocumentFormat.OpenXml/Framework/Schema/CompiledParticle.cs, src/DocumentFormat.OpenXml/Framework/Schema/ParticleCollection.cs, src/DocumentFormat.OpenXml/Framework/Schema/ParticleExtensions.cs, src/DocumentFormat.OpenXml/OpenXmlCompositeElement.cs, test/DocumentFormat.OpenXml.Framework.Tests/Particles/CompiledParticleTests.cs
This change adds an API to simplify adding child elements in the correct order according to the schema definition.
Part of #492
=> Expose `OpenXmlCompositeElement.TryAddChild`

CHANGELOG.md, src/DocumentFormat.OpenXml/OpenXmlCompositeElement.cs
This also removes the generic constraint as that is unnecessary and fails to work in the instances where you have just a `OpenXmlElement`.
=> Rename TryAddChild to AddChild with option for exception

src/DocumentFormat.OpenXml/OpenXmlElement.cs, test/DocumentFormat.OpenXml.Benchmarks/OpenXmlElementDescendantsTests.cs
Reduce property acquisition and repeated call methods to improve performance
|         Method |     Mean |    Error |   StdDev |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|--------------- |---------:|---------:|---------:|---------:|---------:|---------:|----------:|
|    Descendants | 47.73 ms | 0.342 ms | 0.320 ms | 166.6667 | 166.6667 | 166.6667 |     16 MB |
| OldDescendants | 50.80 ms | 0.789 ms | 0.699 ms | 200.0000 | 200.0000 | 200.0000 |     16 MB |
Benchmark code: https://github.com/dotnet-campus/Open-XML-SDK/blob/3f7608a23ba3420d382050c2ca5c7f295a5d381b/test/DocumentFormat.OpenXml.Benchmarks/OpenXmlElementDescendantsTests.cs
=> Reduce property acquisition and repeated call methods 

src/DocumentFormat.OpenXml/OpenXmlElement.cs, test/DocumentFormat.OpenXml.Benchmarks/OpenXmlElementAddNamespaceDeclarationTests.cs
|                     Method |     Mean |     Error |   StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------------------------- |---------:|----------:|---------:|------:|------:|------:|----------:|
|    AddNamespaceDeclaration | 3.665 us | 0.5911 us | 1.658 us |     - |     - |     - |         - |
| OldAddNamespaceDeclaration | 4.303 us | 0.8884 us | 2.462 us |     - |     - |     - |         - |
Because the method execution time is too short, it is difficult to observe the intensity of optimization.
Benchmark code: https://github.com/dotnet-campus/Open-XML-SDK/blob/5d5c307a55066fccb3913d28bf945b51e0a6fcde/test/DocumentFormat.OpenXml.Benchmarks/OpenXmlElementAddNamespaceDeclarationTests.cs
=> Small performance improvements for AddNamespaceDeclaration

CHANGELOG.md, src/DocumentFormat.OpenXml/DocumentFormat.OpenXml.csproj, src/DocumentFormat.OpenXml/Packaging/OpenSettings.cs, src/DocumentFormat.OpenXml/Packaging/OpenXmlPackage.cs, src/DocumentFormat.OpenXml/Packaging/RelationshipErrorHandler.cs, src/DocumentFormat.OpenXml/Resources/ExceptionMessages.Designer.cs, src/DocumentFormat.OpenXml/Resources/ExceptionMessages.resx, src/DocumentFormat.OpenXml/System/Xml/Linq/XDocumentExtensions.cs, test/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/DocumentOpenTests.cs
Since .NET 4.5, there has been issues using the SDK with relationships that have malformed URIs. Specifically, this seems to be seen when docs have hyperlinks that are not valid URIs. This change adds a handler to rewrite this upon opening a document in case they exist. Subsequent user code can handle any other manipulation that is needed (such as removal of the offending hyperlink).
Fixes #715
=> Add a relationship rewriter to help sanitize malformed URIs

CHANGELOG.md, src/DocumentFormat.OpenXml/OpenXmlPartReader.cs, src/DocumentFormat.OpenXml/OpenXmlReader.cs, src/DocumentFormat.OpenXml/XmlConvertingReader.cs, src/DocumentFormat.OpenXml/XmlConvertingReaderFactory.cs, src/DocumentFormat.OpenXml/XmlLineInfo.cs, test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlReaderTest.cs
Provides ability to track the line number and position while reading a part. This is only available on implementations that operate on text itself; implementations such as the `OpenXmlDomReader` operate on nodes which don't have line information anymore.
Fixes #803
=> Provide IXmlLineInfo from OpenXmlReader when available

build/azure-pipelines.yml
The myget feed we've been using has been retired. Removing it from the deployment process.
=> Remove deployment to myget

CHANGELOG.md, src/DocumentFormat.OpenXml/Packaging/RelationshipErrorHandler.cs, test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlPartTest.cs
* An empty string is a valid relative URI (https://tools.ietf.org/html/rfc3986#section-4.2)
* System.IO.Packaging.InternalRelationshipCollection rejects empty `Target` attributes as the absence of a required attribute (https://github.com/dotnet/runtime/blob/7ed93fa9211fcb8719fde13c540a46aa5b5d74fe/src/libraries/System.IO.Packaging/src/System/IO/Packaging/InternalRelationshipCollection.cs#L338-L340)
* Instead of throwing an exception and failing to open the file, provide users with the opportunity to rewrite empty URIs in the same manner as other invalid URIs
Resolves #834
=> Fix bug: System.Xml.XmlException thrown when opening SDK-authored document containing an empty URI

CHANGELOG.md, build/azure-pipelines.yml, src/DocumentFormat.OpenXml/AppendOption.cs, src/DocumentFormat.OpenXml/Framework/Schema/ParticleExtensions.cs, src/DocumentFormat.OpenXml/OpenXmlCompositeElement.cs, test/DocumentFormat.OpenXml.Tests/FileFormatVersionExtensionsTests.cs, test/DocumentFormat.OpenXml.Tests/MockedOpenXmlElement.cs, test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlElementTest2.cs
A previous change had added a null check which inadvertantly caused properties to not be able to be set to null. This fixes that so that children properties can again be set to null.
Fixes #829
=> Fix broken property setters to allow null

src/DocumentFormat.OpenXml/OpenXmlPartReader.cs, src/DocumentFormat.OpenXml/OpenXmlReader.cs, test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlReaderTest.cs
Changes discussed in #848 @twsouthwick
=> Openxmlreader ignorews option

src/DocumentFormat.OpenXml/OpenXmlPartReader.cs, test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlReaderTest.cs
Added more test cases for the ignoreWhitespace=false option and fixes to handle these cases.
@twsouthwick don't know what you prefer. If you want to remove the changes done in https://github.com/OfficeDev/Open-XML-SDK/pull/857 or if you would like to fix the introduced issues. I wasn't aware that changing the xml reader settings will break the internal state handling of the OpenXMLReader
=> Improve whitespace handling

README.md
The msdn forums are deprecated and new forum questions should be posted to the "office-addins-dev" tag per https://docs.microsoft.com/en-us/answers/products/m365 under Office Client development
=> Update README.md to point to new Q&A forums

src/DocumentFormat.OpenXml/Spreadsheet/CellValue.cs, test/DocumentFormat.OpenXml.Tests/Spreadsheet/CellTests.cs, test/DocumentFormat.OpenXml.Tests/Spreadsheet/CellValueTests.cs
Follow-up to #890 . This fixes a validation issue where numbers in exponential format were not recognised.
=> Allow exponents for numeric cell values

CHANGELOG.md, src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_word_2012_wordml.g.cs, src/DocumentFormat.OpenXml/Office2013/Word/Word.cs
- remove validation requirement for CT_Person contact attribute.
=> Make CT_Person contact property "obsolete" with note for future removal.

CHANGELOG.md, global.json, src/DocumentFormat.OpenXml/OpenXmlElement.cs, src/DocumentFormat.OpenXml/SimpleTypes/EnumInfoLookup.cs, src/DocumentFormat.OpenXml/Validation/Semantic/IndexReferenceConstraint.cs, src/DocumentFormat.OpenXml/Validation/Semantic/ReferenceExistConstraint.cs, src/DocumentFormat.OpenXml/Validation/Semantic/UniqueAttributeValueConstraint.cs, src/DocumentFormat.OpenXml/Validation/StateManager.cs, src/DocumentFormat.OpenXml/Validation/ValidationContext.cs, test/DocumentFormat.OpenXml.Tests/TestDocx01.cs, test/DocumentFormat.OpenXml.Tests/ofapiTest/BugRegressionTest.cs
If a document happened to have a large number of elements that have the
UniqueAttributeValueConstraint validation, it will end up recalculating
the values for the constraint way too often. This was because the
constraint was generating the cached lookup with a key using the
attribute text itself. This change updates the lookup to cache all
possible duplicates for the element in question so it only has to be
searched once.
Fixes #918
=> Cache search better in UniqueAttributeValueConstraint

src/DocumentFormat.OpenXml/OpenXmlCompositeElement.cs, src/DocumentFormat.OpenXml/OpenXmlElement.cs
The MaybeNull attribute is redundant in these cases - the nullability is well covered by the NotNullIfNotNull attribute solely.
=> Fix various nullability problems in OpenXmlCompositeElement and OpenXmlElement

src/DocumentFormat.OpenXml/SimpleTypes/OpenXmlComparableSimpleReference.cs, test/DocumentFormat.OpenXml.Tests/SimpleTypes/OpenXmlComparableSimpleReferenceTests.cs
=> Fix nullability annotations of OpenXmlComparableSimpleReference

test/DocumentFormat.OpenXml.Tests/Spreadsheet/CellValueTests.cs
On machines (e.g., German) that do not use the invariant culture, the CellDoubleTest() unit test fails because it computes incorrect expected string values for 1.5 and -1.5 (e.g., "1,5" and "-1,5"). This PR fixes that.
=> Fix CellDoubleTest

Open-XML-SDK.sln, docs/Features.md, src/DocumentFormat.OpenXml.Features/Disposable/DisposableFeatureExtensions.cs, src/DocumentFormat.OpenXml.Features/Disposable/IDisposableFeature.cs, src/DocumentFormat.OpenXml.Features/DocumentFormat.OpenXml.Features.csproj, src/DocumentFormat.OpenXml/ElementEventArgs.cs, src/DocumentFormat.OpenXml/Framework/Features/EventType.cs, src/DocumentFormat.OpenXml/Framework/Features/FeatureEventArgs.cs, src/DocumentFormat.OpenXml/Framework/Features/FeatureEvent{TArg}.cs, src/DocumentFormat.OpenXml/Framework/Features/IFeatureEvent.cs, src/DocumentFormat.OpenXml/Framework/Features/IPackageEventsFeature.cs, src/DocumentFormat.OpenXml/Framework/Features/IPartEventsFeature.cs, src/DocumentFormat.OpenXml/Framework/Features/IPartRootEventsFeature.cs, src/DocumentFormat.OpenXml/Framework/Features/IRaiseFeatureEvent.cs, src/DocumentFormat.OpenXml/Framework/Features/PackageEventExtensions.cs, src/DocumentFormat.OpenXml/Framework/Features/PartEventExtensions.cs, src/DocumentFormat.OpenXml/Framework/Features/PartRootEventExtensions.cs, src/DocumentFormat.OpenXml/OpenXmlPartRootElement.cs, src/DocumentFormat.OpenXml/Packaging/OpenXmlPackage.cs, src/DocumentFormat.OpenXml/Packaging/OpenXmlPackageExtensions.cs, src/DocumentFormat.OpenXml/Packaging/OpenXmlPart.cs, src/DocumentFormat.OpenXml/Packaging/OpenXmlPartContainer.cs, src/DocumentFormat.OpenXml/Packaging/PartDictionary.cs, test/DocumentFormat.OpenXml.Framework.Features.Tests/DisposableFeatureTests.cs, test/DocumentFormat.OpenXml.Framework.Features.Tests/DocumentFormat.OpenXml.Framework.Features.Tests.csproj, test/DocumentFormat.OpenXml.Framework.Features.Tests/TestFeatureCollection.cs, test/DocumentFormat.OpenXml.Framework.Tests/Features/PackageEventsTests.cs
This adds a couple of features that require changes to the internal
implementation of the parts/packages to provide notifications of
changes such as parts being added/removed or the package being
closed.
An additional feature that is implemented in a separate
assembly allows to register items that need to be disposed when the
feature is done which builds on the lifecycle features added in the
main assembly.
=> Add lifetime features and additional library to hold new features

src/DocumentFormat.OpenXml/GeneratedCode/schemas-microsoft-com_office_excel.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas-microsoft-com_office_office.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas-microsoft-com_vml.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_2009_07_customui.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_drawing_2010_main.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_powerpoint_2010_main.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_powerpoint_2012_main.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_spreadsheetml_2009_9_main.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_spreadsheetml_2010_11_ac.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_spreadsheetml_2010_11_main.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_thememl_2012_main.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_webextensions_webextension_2010_11.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_openxmlformats_org_drawingml_2006_chart.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_openxmlformats_org_drawingml_2006_chartDrawing.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_openxmlformats_org_drawingml_2006_compatibility.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_openxmlformats_org_drawingml_2006_diagram.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_openxmlformats_org_drawingml_2006_main.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_openxmlformats_org_drawingml_2006_picture.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_openxmlformats_org_drawingml_2006_spreadsheetDrawing.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_openxmlformats_org_drawingml_2006_wordprocessingDrawing.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_openxmlformats_org_officeDocument_2006_custom-properties.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_openxmlformats_org_officeDocument_2006_docPropsVTypes.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_openxmlformats_org_presentationml_2006_main.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_openxmlformats_org_spreadsheetml_2006_main.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_openxmlformats_org_wordprocessingml_2006_main.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/www_w3_org_2003_04_emma.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/www_w3_org_2003_InkML.g.cs, src/DocumentFormat.OpenXml/Validation/Semantic/ReferenceExistConstraint.cs
This may lead to some prefixes that are not correct, but it matches the
actual schematron items we use. This had been cleaned up on the backend,
but required loading the SDK file itself in order to do so. By breaking
that dependency, we must now do the same logic. This is being done in
the TryFindAttribute method and does the following:
- Check if there is an exact match. Returns that if found
- Find a match by name only as a back up
=> Use full qualified name in semantic validation

src/DocumentFormat.OpenXml.Linq/Feature/IPartRootXElementFeature.cs, src/DocumentFormat.OpenXml.Linq/Feature/OpenXmlLinqExtensions.cs, src/DocumentFormat.OpenXml.Linq/Feature/RootXElementFeature.cs, src/DocumentFormat.OpenXml.Linq/PublicAPI.Unshipped.txt, test/DocumentFormat.OpenXml.Linq.Tests/OpenXmlPartTests.cs
This PR enhances the `RootXElementFeature`, `IPartRootXElementFeature`, and `OpenXmlLinqExtensions` by adding the capability to work with both `XElement` and `XDocument` representations. It adds the following properties and extension methods to the public API:
```csharp
public interface IPartRootXElementFeature
{
XDocument Document { get; set; }
}
public static class OpenXmlLinqExtensions
{
XDocument GetXDocument(this OpenXmlPart part);
void SetXDocument(this OpenXmlPart part, XDocument document);
void SaveXDocument(this OpenXmlPart part);
}
```
The `SaveXDocument` extension method is only added for naming consistency with the `GetXDocument` and `SetXDocument` methods. It has the exact same effect as calling `part.SaveXElement()`.
Calling `part.GetXElement()` has the same effect as …
=> Enhance Linq feature

CHANGELOG.md, src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_drawing_2008_diagram.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_spreadsheetml_2011_1_ac.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_spreadsheetml_2014_revision.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_openxmlformats_org_spreadsheetml_2006_main.g.cs, test/DocumentFormat.OpenXml.Framework.Tests/ElementChildren.json, test/DocumentFormat.OpenXml.Packaging.Tests/data/Particles.json, test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlValidatorTest.cs
DocumentFormat.OpenXml.Office.Drawing.ShapeTree is available in Office 2010 and above, not 2007.
DocumentFormat.OpenXml.Office2010.ExcelAc changed to DocumentFormat.OpenXml.Office2013.ExcelAc
=> fixes a couple historical namespace issues

gen/DocumentFormat.OpenXml.Generator/OpenXmlGeneratorContext.cs
This will allow the exception to be thrown from within a generator if it occurs. By so doing, it will be surfaced better in VS and other tools rather than a TypeLoadException
=> Store shared context in a lazy

gen/DocumentFormat.OpenXml.Generator.Linq/Properties/launchSettings.json, src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_drawing_2021_oembed.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_drawing_2021_scriptlink.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_powerpoint_2021_06_main.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_microsoft_com_office_word_2020_oembed.g.cs, src/DocumentFormat.OpenXml/GeneratedCode/schemas_openxmlformats_org_drawingml_2006_main.g.cs, src/DocumentFormat.OpenXml/PublicAPI/PublicAPI.Unshipped.txt, test/DocumentFormat.OpenXml.Framework.Tests/ElementChildren.json, test/DocumentFormat.OpenXml.Packaging.Tests/data/Particles.json
this update renames the C# namespaces only for the new Microsoft 365 subscription model types and constraints that were just released.
=> refactor C# namespace to map xmlns URIs

README.md
I've added OfficeIMO (https://github.com/EvotecIT/OfficeIMO) to related tools. It heavily simplifies working with Microsoft Word documents. Adding sections, page breaks, changing page orientation, adding cover pages, table of contents, and other things is a lot easier than trying to do it manually using OpenXML SDK.
=> Add OfficeIMO to related tools

gen/DocumentFormat.OpenXml.Generator.Linq/Program.cs, src/DocumentFormat.OpenXml/Features/FeatureCollection.cs, src/DocumentFormat.OpenXml/Features/IElementMetadataFeature.cs, src/DocumentFormat.OpenXml/Features/StaticTypesFeatures.cs, src/DocumentFormat.OpenXml/Framework/Metadata/ElementMetadataProviderFeature.cs, src/DocumentFormat.OpenXml/Framework/OpenXmlNamespace.cs, src/DocumentFormat.OpenXml/OpenXmlElement.cs, src/DocumentFormat.OpenXml/OpenXmlPartReader.cs, src/DocumentFormat.OpenXml/Packaging/OpenXmlPart.cs, src/DocumentFormat.OpenXml/Packaging/OpenXmlPartContainer.cs, src/DocumentFormat.OpenXml/Packaging/PresentationDocument.cs, src/DocumentFormat.OpenXml/Packaging/SpreadsheetDocument.cs, src/DocumentFormat.OpenXml/Packaging/WordprocessingDocument.cs
This is an initial attempt at separating out the infrastructure for
statically typed classes from the framework. This updates things to
start explicitly depending on the generated classes if they are needed.
Over time, we should be able to separate out the generated classes into
their own assembly and keep a "framework" of OpenXml related
functionality.
=> Create separate features for statically typed classes

gen/DocumentFormat.OpenXml.Generator.Linq/Program.cs, src/DocumentFormat.OpenXml/AlternateContent.cs, src/DocumentFormat.OpenXml/Features/OpenXmlNamespaceResolver.cs, src/DocumentFormat.OpenXml/Framework/Metadata/ElementMetadata.cs, src/DocumentFormat.OpenXml/Framework/Metadata/ElementMetadataProviderFeature.cs, src/DocumentFormat.OpenXml/Framework/NamespaceExtensions.cs, src/DocumentFormat.OpenXml/Framework/OpenXmlNamespace.cs, src/DocumentFormat.OpenXml/Framework/OpenXmlQualifiedName.cs, src/DocumentFormat.OpenXml/Framework/PrefixName.cs, src/DocumentFormat.OpenXml/Framework/SchemaAttrAttribute.cs, src/DocumentFormat.OpenXml/MCContext.cs, src/DocumentFormat.OpenXml/OpenXmlAttribute.cs, src/DocumentFormat.OpenXml/OpenXmlCompositeElement.cs, src/DocumentFormat.OpenXml/OpenXmlElement.cs, src/DocumentFormat.OpenXml/OpenXmlElementExtensionMethods.cs, src/DocumentFormat.OpenXml/OpenXmlPartReader.cs, src/DocumentFormat.OpenXml/OpenXmlPartRootElement.cs, src/DocumentFormat.OpenXml/OpenXmlUnknownElement.cs, src/DocumentFormat.OpenXml/Packaging/RelationshipCollection.cs, src/DocumentFormat.OpenXml/XmlConvertingReader.cs, test/DocumentFormat.OpenXml.Framework.Tests/OpenXmlNamespaceTests.cs, test/DocumentFormat.OpenXml.Framework.Tests/PropertyBuilderTests.cs, test/DocumentFormat.OpenXml.Tests/Extensions/OpenXmlElementExtensions.cs
This value can be retrieved from the IOpenXmlNamespaceResolver when needed rather than at construction. This simplifies the usage of this type drastically and makes it something we should probably just expose publicly.
=> Remove prefix property

src/DocumentFormat.OpenXml/Packaging/OpenXmlPackage.FlatOpc.cs, test/DocumentFormat.OpenXml.Tests/Documents/DocumentTests.FlatOpcTests.cs
Using Stream.Read does not guarantee the requested bytes are read. This started failing in a test on .NET 6+, but could potentially fail everywhere this API is used without checking the return value
=> Fix stream copy

src/DocumentFormat.OpenXml/Features/IPartUriFeature.cs, src/DocumentFormat.OpenXml/Packaging/CloneExtensions.cs, src/DocumentFormat.OpenXml/Packaging/OpenXmlPackage.cs, src/DocumentFormat.OpenXml/Packaging/PartUriHelper.cs, src/DocumentFormat.OpenXml/Packaging/TypedOpenXmlPackage.cs, test/DocumentFormat.OpenXml.Packaging.Tests/PartUriHelperTests.cs, test/DocumentFormat.OpenXml.Tests/SaveAndCloneTests.cs
This replaces direct calls to PartUriHelper with an indirection via IPartUriFeature. When cloning, this feature will be replaced so that it doesn't try to get a different URI.
Fixes #1197
=> Don't change part URIs on cloning (or SaveAs)

Directory.Build.props, Directory.Build.targets, build/azure-pipelines.yml, build/build.yml, build/package.yml, src/DocumentFormat.OpenXml/DocumentFormat.OpenXml.csproj, test/DocumentFormat.OpenXml.Framework.Tests/DocumentFormat.OpenXml.Framework.Tests.csproj
.NET 5.0 is out of support and the new STS is .NET 7.0. We no longer need to build/test on this configuration
=> Remove .NET 5.0 requirement

src/DocumentFormat.OpenXml/Packaging/OpenXmlPackage.FlatOpc.cs, src/common/FrameworkShims.targets, src/common/System/IO/StreamReadExtensions.cs
There is an unnecessary allocation in PR #1232: it allocates a new byte array via `MemoryStream.ToArray()`.
It's possible to avoid this call and read the data into a byte array directly, as it was done before (but was broken due to the [net6 breaking change](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams)).
=> FlatOpc: avoid unnecessary MemoryStream.ToArray call

.gitignore, build/sign.yml
.NET Core 2.1 is now out of support, but the codesigning task requires it. This change also adds some files we don't need to track to .gitignore
=> Include .NET Core 2.1 runtime for signing task

src/DocumentFormat.OpenXml.Framework/Packaging/OpenSettings.cs, src/DocumentFormat.OpenXml.Framework/Packaging/OpenXmlPartContainer.cs
This is the simple approach of ignoring the missing part but leaving the relationship entry alone. Excel will handle this but if we feel it's better to remove the relationship, I can rework the fix.
=> fix for issue1281, ignore missing calcChain part

src/DocumentFormat.OpenXml.Framework/Features/IRelationshipFilterFeature.cs, src/DocumentFormat.OpenXml.Framework/Features/PackageFeatureBase.cs, src/DocumentFormat.OpenXml.Framework/Features/PackageStorageExtensions.cs, src/DocumentFormat.OpenXml.Framework/Packaging/Builder/PackageRelationshipBuilder.cs, src/DocumentFormat.OpenXml.Framework/Packaging/PackageUriHandlingExtensions.cs, test/DocumentFormat.OpenXml.Framework.Tests/Features/PackageUriHandlingTests.cs
This allows for a callback to be registered that will filter out how relationships are defined without needing to override IPackagePart implementations.
=> Add relationship filter to reduce overriding package parts

src/DocumentFormat.OpenXml.Framework/Features/PackageFeatureBase.cs, src/DocumentFormat.OpenXml.Framework/Features/PackageStorageExtensions.cs, src/DocumentFormat.OpenXml.Framework/Features/RelationshipFilterExtensions.cs, src/DocumentFormat.OpenXml.Framework/Packaging/Builder/PackageRelationshipBuilder.cs, src/DocumentFormat.OpenXml.Framework/Packaging/OpenSettings.cs, src/DocumentFormat.OpenXml.Framework/Packaging/PartRelationshipsFeature.cs, src/DocumentFormat.OpenXml/Packaging/SpreadsheetDocument.cs, src/DocumentFormat.OpenXml/Packaging/SpreadsheetDocumentExtensions.cs, test/DocumentFormat.OpenXml.Packaging.Tests/OpenXmlPackageTests.cs
This changes the relationship filtering to use the `IRelationshipFilterFeature` to register ignorable relationships. As part of this, the `OpenSettings.IgnoreExceptionOnCalcChainPartMissing` property has been removed and a new extension method has been added that can be opted into.
Fixes #1281
=> Use relationship filter for calcChain and recovered types

.github/workflows/codeql-analysis.yml
https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
=> update codeQL GitHub action to v2

.github/workflows/codeql-analysis.yml
https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
=> update codeQL GitHub action to v2 for v2.20.0

src/DocumentFormat.OpenXml.Framework/SimpleTypes/Base64BinaryValue.cs, src/DocumentFormat.OpenXml.Framework/SimpleTypes/EnumValue.cs, src/DocumentFormat.OpenXml.Framework/SimpleTypes/OpenXmlComparableSimpleValue.cs
While investigating enabling nullable annotations in [ClosedXml](https://github.com/ClosedXML/ClosedXML) I came across some problems with code like so (simplified and manually created to demonstrate):
```c#
var properties = new SheetFormatProperties();
DoubleValue? openXmlComparableSimpleValue = properties.DefaultRowHeight;
if (openXmlComparableSimpleValue != null)
{
return;
}
```
Gives: `Possible null reference argument for parameter 'left' in 'DocumentFormat.OpenXml.OpenXmlComparableSimpleValue<T>.operator !='` 
I went through operator overloads and annotated ones allowing null values with `?` when input as null is handled properly.
=> Allow null values via annotation to operator overloads able to handle null

Directory.Build.props, docs/Diagnostics.md, src/DocumentFormat.OpenXml.Framework/DiagnosticIds.cs, src/DocumentFormat.OpenXml.Framework/Features/PackageFeatureBase.cs, src/DocumentFormat.OpenXml.Framework/FileFormatVersionExtensions.cs, src/DocumentFormat.OpenXml.Framework/OpenXmlMiscNode.cs, src/DocumentFormat.OpenXml.Framework/Packaging/Builder/DelegatingPackageFeature.cs, src/DocumentFormat.OpenXml.Framework/Packaging/IPackage.cs, src/DocumentFormat.OpenXml.Framework/Packaging/IPackagePart.cs, src/DocumentFormat.OpenXml.Framework/Packaging/IPackageProperties.cs, src/DocumentFormat.OpenXml.Framework/Packaging/IPackageRelationship.cs, src/DocumentFormat.OpenXml.Framework/Packaging/IRelationshipCollection.cs, src/DocumentFormat.OpenXml.Framework/Packaging/OpenXmlPackage.cs, src/DocumentFormat.OpenXml.Framework/Packaging/PackageExtensions.cs, src/common/FrameworkShims.targets, src/common/System/ObsoleteAttribute.cs
This will enable users to retrieve the underlying package, but it is marked as experimental using obsolete. If using a newer compiler, this may be suppressed with the associated diagnostic id, otherwise, it will just show up as obsoleted APIs with the message.
Fixes #1400
=> Expose IPackage and related APIs

Directory.Build.props, src/Directory.Build.props, src/DocumentFormat.OpenXml.Features/DocumentFormat.OpenXml.Features.csproj, src/DocumentFormat.OpenXml.Framework/DocumentFormat.OpenXml.Framework.csproj, src/DocumentFormat.OpenXml.Linq/DocumentFormat.OpenXml.Linq.csproj, src/DocumentFormat.OpenXml/DocumentFormat.OpenXml.csproj
This does not change any support, but only the framework library needs
to be built against so many targets. The rest are sufficient with .NET
3.5, .NET 4.0, and .NET Standard 2.0 as they mostly build on things in
the framework.
=> Reduce unnecessary target builds

data/schemas/schemas_openxmlformats_org_drawingml_2006_diagram.json, generated/DocumentFormat.OpenXml.Linq/DocumentFormat.OpenXml.Generator/DocumentFormat.OpenXml.Generator.OpenXmlGenerator/Linq.NoNamespace.g.cs, generated/DocumentFormat.OpenXml/DocumentFormat.OpenXml.Generator/DocumentFormat.OpenXml.Generator.OpenXmlGenerator/schemas_openxmlformats_org_drawingml_2006_diagram.cs
this was a typo in our backend generation.
=> changed HightScale to HeightScale

.github/workflows/benchmarks.yml, Directory.Build.props, Directory.Build.targets, src/Directory.Build.targets, src/DocumentFormat.OpenXml.Features/ParagraphId/ParagraphIdOptions.cs, src/DocumentFormat.OpenXml.Framework/DocumentFormat.OpenXml.Framework.csproj, src/DocumentFormat.OpenXml.Linq/DocumentFormat.OpenXml.Linq.csproj, src/DocumentFormat.OpenXml/DocumentFormat.OpenXml.csproj, src/PEVerify.targets, test/Directory.Build.targets, test/DocumentFormat.OpenXml.Benchmarks/DocumentFormat.OpenXml.Benchmarks.csproj
Cleans up references for System.IO.Packaging where not needed
=> Remove unnecessary dependency

.github/workflows/package.yml
* Package signing only happens on release
* Checking for release does not require signing
=> Update GitHub Actions

src/DocumentFormat.OpenXml.Framework/OpenXmlPartRootElement.cs
With this change, it's possible to do this: 
```csharp
OpenXmlPartRootElement partRoot = pShape.Ancestors<OpenXmlPartRootElement>().First();
if (partRoot.OpenXmlPart is null)
{
Console.WriteLine("partRoot is null");
return;
}
OpenXmlPart part = partRoot.OpenXmlPart;
```
=> allow access to part from elements

.github/workflows/package.yml
- Need to use 5.10.0 per https://github.com/GitTools/GitVersion/issues/2838
- 6.x will remove NuGetSemVer2
=> Push to CI feed

CHANGELOG.md, src/DocumentFormat.OpenXml.Framework/Features/PackageFeatureBase.cs, src/DocumentFormat.OpenXml.Framework/Features/StreamPackageFeature.cs, src/DocumentFormat.OpenXml.Framework/Packaging/WriteableStreamExtensions.cs, src/DocumentFormat.OpenXml.Framework/Resources/ExceptionMessages.Designer.cs, src/DocumentFormat.OpenXml.Framework/Resources/ExceptionMessages.resx, test/DocumentFormat.OpenXml.Framework.Tests/DocumentFormat.OpenXml.Framework.Tests.csproj, test/DocumentFormat.OpenXml.Tests.Assets/IFile.cs, test/DocumentFormat.OpenXml.Tests.Assets/TemporaryFile.cs, test/DocumentFormat.OpenXml.Tests.Assets/TestAssets.cs, test/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/DocumentOpenTests.cs
- We must be able to seek to create a temporary file requried for uri handling
- We should throw the same exception we did in v2.x
- If compat mode is on, this will throw at open time (i.e. it will eagerly load everything)
Fixes #1636
=> Check for seekable stream for malformed uri handling

src/DocumentFormat.OpenXml.Framework/Packaging/WriteableStreamExtensions.cs
Cleaning up the temporary file and adding a comment about ownership
Fixes #1658
=> Register temp file for dispose

CHANGELOG.md, gen/DocumentFormat.OpenXml.Generator.Models/Schematron/KnownSchematrons/Schematron1_3.cs, gen/DocumentFormat.OpenXml.Generator.Models/Schematron/StringSchematronVisitor.cs
Meta-code generation assumes a dot as decimal point, which is not the case in French, for instance. If the host build context is using a french locale, the project could not be built.
Adding a few `System.Globalization.CultureInfo.InvariantCulture` fixes the problem.
#1657
=> fixed meta-code generation for non-english host build context

Directory.Packages.props, test/DocumentFormat.OpenXml.Generator.Tests/DocumentFormat.OpenXml.Generator.Tests.csproj
Remove NuGet.Packaging.Core since it only contains type forwarders.
=> Remove NuGet.Packaging.Core, as it's an assembly that only contains forwarders

.github/workflows/release.yml
This is to tighten security for nuget deployment.
=> Increase approvers to 2 for deployment.

Directory.Packages.props
=> Update System.IO.Packaging to 8.0.1

src/DocumentFormat.OpenXml.Framework/OpenXmlPartRootElement.cs, src/DocumentFormat.OpenXml.Framework/Packaging/OpenXmlPart.cs
=> Get strict relationship status before opening stream

README.md
- Update `Download` to `Stable` to compared with `Prerelease`
- Update `Prerelease` nuget package badge link to absolute latest version
=> docs: update nuget badge

src/DocumentFormat.OpenXml/Packaging/CoreFilePropertiesPart.cs
This allows CoreFilePropertiesPart to access package properties via the parent package properties per discussion in #389 .
=> add extension to CoreFilePropertiesPart to access package properties

README.md
includes info from Thomas Barnekow and simplifies the Note on breaking changes in v 3.0.0
=> Clarified description of the SDK in README.md

src/DocumentFormat.OpenXml.Framework/EnumerableExtensions.cs, src/DocumentFormat.OpenXml.Framework/Resources/ExceptionMessages.Designer.cs, src/DocumentFormat.OpenXml.Framework/Resources/ExceptionMessages.resx, src/DocumentFormat.OpenXml.Framework/Validation/Semantic/RelationshipTypeConstraint.cs, src/DocumentFormat.OpenXml.Framework/Validation/Semantic/SemanticConstraint.cs
=> Refactor to clean up CA1851 warnings

gen/DocumentFormat.OpenXml.Generator.Models/Generators/Elements/DataModelWriterExtensions.cs, generated/DocumentFormat.OpenXml/DocumentFormat.OpenXml.Generator/DocumentFormat.OpenXml.Generator.OpenXmlGenerator/schemas_microsoft_com_office_drawing_2012_chart.g.cs
this pr obsoletes the properties mentioned in #1769 
it also adds code to the generator to add code attributes like ObsoleteAttribute to complex type classes, child elements and attributes.
=> obsolete several child elements removed in Office 2015

src/DocumentFormat.OpenXml.Framework/Validation/DocumentValidator.cs
- closes #1223 
- closes #1190 
- closes #1142
=> add note to Validate documentation to specify that it only validates the transitional format

src/DocumentFormat.OpenXml.Framework/OpenXmlPartReader.cs, test/DocumentFormat.OpenXml.Packaging.Tests/OpenXmlPartReaderTests.cs
=> Fixes #1933 - CreateElement calls now parametrized UnknownOpenXmlElement constructor
